config/routes.rb
Paper::Application.routes.draw do
  match 'login' => 'user_sessions#new'
  match 'logout' => 'user_sessions#destroy'

  resources :user_sessions, :only => [:new, :create, :destroy]

  resources :plays, :only => :create do
    #noinspection RailsParamDefResolve
    resource :star, :controller => 'play_stars', :only => [:create, :destroy]
  end

  resources :pictures, :only => :show

  resources :users, :only => [:index, :show, :create, :update] do
    member do
      post :friend
      get :friend, :action => :confirm_friend
      post :unfriend
      get :unfriend, :action => :confirm_unfriend
      post :block
      get :block, :action => :confirm_block
      post :unblock
      get :unblock, :action => :confirm_unblock
    end
  end

  #noinspection RailsParamDefResolve
  resource :account, :controller => 'users', :only => [:edit, :new, :show, :destroy] do
    member do
      get :games
      get :delete
      get 'resend_confirmation/:login', :action => 'resend_confirmation', :as => 'resend_confirmation'
      get 'confirm/:confirmation_code', :action => 'confirm', :as => 'confirm'
    end
    resource :login_reminder, :only => [:new, :create]
    resources :password_resets, :only => [:new, :create, :edit, :update]
  end

  resources :games do
    #noinspection RailsParamDefResolve
    resources :messages, :controller => 'game_messages', :only => [:create, :destroy]
    resources :sequences, :only => :show
    resources :players, :only => [] do
      member do
        post :eject
      end
    end
    resources :invitations, :only => [:new, :create], :shallow => true do
      member do
        post :accept
        post :decline
      end
    end
    resource :user_token, :controller => 'game_user_tokens', :only => [:show]
    member do
      post :join
      get :join, :action => :confirm_join
      post :leave
      get :leave, :action => :confirm_leave
      post :start
      get :start, :action => :confirm_start
      get :colors
    end
  end

  resources :players, :only => [] do
    resource :user_token, :controller => 'player_user_tokens', :only => [:show]
  end

  resources :pages, :only => [:show]
  
  resources :authentications, :only => [:create, :destroy]
  match '/auth/:provider/callback' => 'authentications#create'

  resource :notifications do
    get :send_daily_digest
  end

  root :to => 'pages#home'
  match 'example' => 'pages#example'
end

app/views/notifier/daily_digest.html.erb
<h1>The Paper Game Daily Digest</h1>
<p>Hi <%= @login %>,</p>
<p>You have pending plays:</p>
<ul>
    <% @games.each do |game| %>
      <li>
        <%= link_to game[1]['name'], game_url(game[0]) %> (<%= game[1]['count'] %>)
          <% game[1]['plays'].each do |is_picture| %>
            <% if is_picture %>
              <%= image_tag image_url('picture.png'), :alt => 'Picture', :title => 'Picture', :style => 'margin: 0 0 0 5px;' %>
            <% else %>
              <%= image_tag image_url('sentence.png'), :alt => 'Sentence', :title => 'Sentence', :style => 'margin: 0 0 0 5px;' %>
            <% end %>
          <% end %>
      </li>
    <% end %>
</ul>

app/views/notifier/email_confirmation_instructions.erb
Thank you for joining The Paper Game! Click the url below to activate your account!

<%= @account_activation_url %>

If the above URL does not work, try copying and pasting it into your browser's address bar.
If you continue to have problems, please feel free to contact us.

app/views/notifier/email_confirmation_instructions.html.erb
<h1>Thank you for joining The Paper Game!</h1>
<p>Click the url below to confirm your email address:</p>
<p><%= link_to @account_activation_url, @account_activation_url %></p>
<p>
  If the above URL does not work, try copying and pasting it into your browser's address bar.
  If you continue to have problems, please feel free to contact us.
</p>

app/views/notifier/game_complete.erb
A game has finished!
Check out the results, and vote for your favorite plays!
<%= game_url(@game) %>

app/views/notifier/game_complete.html.erb
<h1>A game has finished!</h1>
<p>Check out the results, and vote for your favorite plays!</p>
<p><%= link_to @game.name, game_url(@game) %></p>

app/views/notifier/login_reminder.erb
The Paper Game Login Reminder

Someone requested a login name reminder from The Paper Game for this email address. The login associated with this email address is:

<%= @login %>

app/views/notifier/login_reminder.html.erb
<h1>The Paper Game Login Reminder</h1>
<p>
  Someone requested a login name reminder from The Paper Game for this email address.
  The login associated with this email address is:
</p>
<p><b><%= @login %></b></p>

app/views/notifier/notifier.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/notifier/password_changed_notification.erb
The Paper Game Password Changed

Your password has been updated.

app/views/notifier/password_changed_notification.html.erb
<h1>The Paper Game Password Changed</h1>
<p>Your password has been updated.</p>

app/views/notifier/password_reset_instructions.erb
The Paper Game Password Reset

A password reset request has been made for your account. If you requested this, click the link below the select your new password.

<%= @password_reset_url %>

If the above URL does not work, try copying and pasting it into your browser's address bar.
If you continue to have problems, please feel free to contact us.

app/views/notifier/password_reset_instructions.html.erb
<h1>The Paper Game Password Reset</h1>
<p>A password reset request has been made for your account. If you requested this, click the link below the select your new password.</p>
<p><%= link_to @password_reset_url, @password_reset_url %></p>
<p>
  If the above URL does not work, try copying and pasting it into your browser's address bar.
  If you continue to have problems, please feel free to contact us.
</p>

app/views/notifier/welcome.erb
Welcome to The Paper Game! Your email address has been confirmed.

<%= @root_url %>

app/views/notifier/welcome.html.erb
<h1>Welcome to The Paper Game!</h1>
<p>Your email address has been confirmed.</p>
<p><%= link_to 'Get started!', @root_url %></p>